name: unit-tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unittests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ "3.10", "3.12" ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
        shell: bash

      - name: Install dependencies
        working-directory: ${{ inputs.working_directory }}
        run: |
          uv pip install --system -r pyproject.toml --extra all --extra dev .
        shell: bash

      - name: Test
        run: |
          pytest -v tests/
        shell: bash
