name: unit-tests

on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  unittests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ "3.10", "3.12" ]
    steps:
      - name: Build
        uses: ./.github/actions/build

      - name: Test
        run: |
          pytest -v -m unit tests/
        shell: bash
